var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};$jscomp.owns=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};$jscomp.ASSUME_ES5=!1;
$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,d){if(a==Array.prototype||a==Object.prototype)return a;a[b]=d.value;return a};
$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var d=a[b];if(d&&d.Math==Math)return d}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};
$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(a,b){var d=$jscomp.propertyToPolyfillSymbol[b];if(null==d)return a[b];d=a[d];return void 0!==d?d:a[b]};$jscomp.polyfill=function(a,b,d,e){b&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,b,d,e):$jscomp.polyfillUnisolated(a,b,d,e))};
$jscomp.polyfillUnisolated=function(a,b,d,e){d=$jscomp.global;a=a.split(".");for(e=0;e<a.length-1;e++){var c=a[e];if(!(c in d))return;d=d[c]}a=a[a.length-1];e=d[a];b=b(e);b!=e&&null!=b&&$jscomp.defineProperty(d,a,{configurable:!0,writable:!0,value:b})};
$jscomp.polyfillIsolated=function(a,b,d,e){var c=a.split(".");a=1===c.length;e=c[0];e=!a&&e in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var f=0;f<c.length-1;f++){var k=c[f];if(!(k in e))return;e=e[k]}c=c[c.length-1];d=$jscomp.IS_SYMBOL_NATIVE&&"es6"===d?e[c]:null;b=b(d);null!=b&&(a?$jscomp.defineProperty($jscomp.polyfills,c,{configurable:!0,writable:!0,value:b}):b!==d&&(void 0===$jscomp.propertyToPolyfillSymbol[c]&&(d=1E9*Math.random()>>>0,$jscomp.propertyToPolyfillSymbol[c]=$jscomp.IS_SYMBOL_NATIVE?
$jscomp.global.Symbol(c):$jscomp.POLYFILL_PREFIX+d+"$"+c),$jscomp.defineProperty(e,$jscomp.propertyToPolyfillSymbol[c],{configurable:!0,writable:!0,value:b})))};$jscomp.assign=$jscomp.TRUST_ES6_POLYFILLS&&"function"==typeof Object.assign?Object.assign:function(a,b){for(var d=1;d<arguments.length;d++){var e=arguments[d];if(e)for(var c in e)$jscomp.owns(e,c)&&(a[c]=e[c])}return a};$jscomp.polyfill("Object.assign",function(a){return a||$jscomp.assign},"es6","es3");
(()=>{function a(){if(5<b)return console.log("lzfr is not avaiable"),!1;"undefined"!=typeof window.lzfr?(window.lzfr.getSubmitForm=function(d,e){for(var c={},f=aimktFormConstant.PropertyName,k=aimktFormConstant.CookieName,r=aimktFormConstant.Attribute,g=$jscomp.makeIterator(d.SubmissionProperties),h=g.next();!h.done;h=g.next())h=h.value,c[h.InputName]=h.ContactPropertyValue;(g=this.getUrlParameter(f.UtmSource))&&(c[f.UtmSource]=g);(g=this.getUrlParameter(f.UtmTerm))&&(c[f.UtmTerm]=g);(g=
this.getUrlParameter(f.UtmMedium))&&(c[f.UtmMedium]=g);(g=this.getUrlParameter(f.UtmContent))&&(c[f.UtmContent]=g);(g=this.getUrlParameter(f.UtmCampaign))&&(c[f.UtmCampaign]=g);(g=this.getUrlParameter(f.Gclid))&&(c[f.Gclid]=g);(g=this.getUrlParameter(f.Fbclid))&&(c[f.Fbclid]=g);(g=this.getUrlParameter(f.EmailId))&&(c[f.EmailId]=g);(g=this.getUrlParameter(f.WorkflowId))&&(c[f.WorkflowId]=g);(g=this.getUrlParameter(f.ContactId))&&(c[f.ContactId]=g);c=Object.assign({},c,{ProfileID:this.getCookie(k.UcapProfileID),
TenantID:e.companyID});f=this.STATISTIC+"/api/ucap/eventcollector";try{var n=document.querySelector(".lpage-ucap[lz-id]"),l=null===n?"":n.getAttribute(r.LzID);l||(l="");var m={destinationURL:window.parent.location.href,pagePath:window.parent.location.pathname,pageOrigin:window.parent.location.origin,pageName:window.parent.document.title,referringURL:document.referrer||window.parent.document.referrer,lpageId:l};var t=m.hasOwnProperty("lpageId")?m.lpageId:void 0,p,q;fetch(f,{method:"POST",headers:{Authorization:"Basic "+
btoa("karaf:karaf"),"Content-type":"text/plain; charset=utf-8","Access-Control-Allow-Origin":"*"},body:JSON.stringify({events:[{eventType:202,scope:2,source:{itemType:"landingPageId",properties:m,itemId:t},target:{itemType:"formId",itemId:e.formID,properties:{TargetName:e.name,OwnerID:e.OwnerID,FormKey:e.FormKey}},properties:c}],sessionId:this.getCookie(k.UcapSessionID)})}).then(dataLayer.push({event:"form-submission",mddk:"tu-van",sdt:null==(p=c)?void 0:p.phoneNumber,email:null==(q=c)?void 0:q.email}))}catch(u){console.error("aimarketing_error GET FORM - ",
u)}},console.log("lzfr modified")):(b++,setTimeout(a,1E3))}var b=0;a()})();
